{ lib
, stdenv
, fetchurl
, dpkg
, autoPatchelfHook
, buildFHSEnv
# Runtime deps (from deb Depends)
, qt6
, nss
, nspr
, pcsclite
, gnutls
, glib
, zlib
}:

let
  version = "4.4.1.0";

  # Base derivation: extract deb, patch ELF binaries.
  # This does NOT run standalone due to hardcoded FHS paths in the binary.
  atostek-id-unwrapped = stdenv.mkDerivation {
    pname = "atostek-id-unwrapped";
    inherit version;

    src = fetchurl {
      url = "https://files.fineid.fi/download/atostek/${version}/linux/AtostekID_DEB_${version}.deb";
      # TODO: replace with actual hash after first build
      hash = lib.fakeHash;
    };

    nativeBuildInputs = [
      dpkg
      autoPatchelfHook
    ];

    # Libs that autoPatchelfHook will resolve NEEDED entries against.
    # The binary links: Qt6{Core,Gui,Widgets,Network,Xml,PrintSupport},
    # libnss3, libnspr4, libsmime3, libpcsclite, plus bundled libs.
    buildInputs = [
      qt6.qtbase
      nss
      nspr
      pcsclite
      gnutls
      glib
      zlib
      stdenv.cc.cc.lib  # libstdc++
    ];

    unpackPhase = ''
      dpkg-deb -x $src .
    '';

    installPhase = ''
      runHook preInstall

      # Main binary
      install -Dm755 usr/bin/atostekid $out/bin/atostekid

      # PKCS#11 module (also available as separate package)
      install -Dm755 usr/lib/Atostek-ID-PKCS11.so $out/lib/Atostek-ID-PKCS11.so

      # PIN dialog library (loaded by soname, needs to be findable)
      install -Dm755 usr/lib/libAskPinLibrary.so $out/lib/libAskPinLibrary.so

      # Bundled libraries — these ship specific versions the binary expects
      # (libcrypto 3.3.2, botan-2, qpdf 29, minizip, libjpeg, zlib)
      install -dm755 $out/lib/atostekid
      cp -a usr/lib/atostekid/* $out/lib/atostekid/

      # Documentation
      install -dm755 $out/share/doc/atostekid
      cp -a usr/share/doc/atostekid/* $out/share/doc/atostekid/

      # Browser setup script — patched to use env vars
      install -Dm755 usr/bin/atostekid-setup-user-browser.sh \
        $out/bin/atostekid-setup-user-browser.sh

      # GNOME dconf fragment (enables appindicator extension)
      install -Dm644 etc/dconf/db/local.d/00-extensions-atostekid \
        $out/etc/dconf/db/local.d/00-extensions-atostekid

      runHook postInstall
    '';

    # autoPatchelfHook runs during fixupPhase, so search paths must
    # be registered before it. The bundled libs in lib/atostekid/
    # need to resolve each other (e.g. libqpdf → libcrypto, libjpeg).
    preFixup = ''
      addAutoPatchelfSearchPath $out/lib/atostekid
      addAutoPatchelfSearchPath $out/lib
    '';

    meta = with lib; {
      description = "Atostek ID smart card reader software for Finnish DVV certificate cards";
      homepage = "https://dvv.fi/en/card-reader-software";
      license = licenses.unfree;
      platforms = [ "x86_64-linux" ];
      maintainers = [ ]; # Add yourself
    };
  };

  # Desktop file (not shipped in deb — generated by postinst)
  desktopFile = ''
    [Desktop Entry]
    Type=Application
    Name=Atostek ID
    Exec=atostekid
    Comment=Smart card reader software for Finnish DVV certificate cards
    Categories=Utility;Security;
    StartupNotify=false
  '';

in
# Wrap in FHS environment to satisfy hardcoded absolute paths.
#
# The binary contains these hardcoded references:
#   /usr/lib/Atostek-ID-PKCS11.so
#   /usr/lib/libAskPinLibrary.so  (and /usr/lib/atostekid/ for bundled libs)
#   /usr/bin/atostekid-setup-user-browser.sh
#   /usr/bin/atostekid  (restart command: "pkill atostekid && nohup /usr/bin/atostekid &")
#   /usr/share/applications/atostekid.desktop
#   /usr/share/doc/atostekid/
#   /etc/AtostekIDConfig
#   /etc/atostekid/AtostekID.ini
#   /etc/os-release  (for OS detection)
#   /usr/local/ssl/*  (bundled OpenSSL OPENSSLDIR)
#
buildFHSEnv {
  name = "atostekid";
  inherit version;

  targetPkgs = pkgs: [
    atostek-id-unwrapped
    pcsclite
    nss
    nspr
    gnutls
    qt6.qtbase
    qt6.qtwayland
  ];

  # Symlinks from the unwrapped package into FHS locations.
  # buildFHSEnv merges targetPkgs into /usr, so $out/bin/atostekid
  # becomes /usr/bin/atostekid, $out/lib/... becomes /usr/lib/..., etc.
  # This satisfies all the hardcoded paths above.

  runScript = "atostekid";

  extraInstallCommands = ''
    # Desktop file for application launchers
    mkdir -p $out/share/applications
    cat > $out/share/applications/atostekid.desktop << 'EOF'
    ${desktopFile}
    EOF

    # XDG autostart
    mkdir -p $out/etc/xdg/autostart
    cp $out/share/applications/atostekid.desktop $out/etc/xdg/autostart/
  '';

  meta = atostek-id-unwrapped.meta // {
    mainProgram = "atostekid";
  };

  # Expose the unwrapped package and PKCS#11 path for the NixOS module
  passthru = {
    unwrapped = atostek-id-unwrapped;
    pkcs11Module = "${atostek-id-unwrapped}/lib/Atostek-ID-PKCS11.so";
    browserSetupScript = "${atostek-id-unwrapped}/bin/atostekid-setup-user-browser.sh";
  };
}
